/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as AuthorNameRouteImport } from './routes/author.$name'
import { Route as TrackIdEditRouteImport } from './routes/track.$id.edit'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorNameRoute = AuthorNameRouteImport.update({
  id: '/author/$name',
  path: '/author/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdEditRoute = TrackIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TrackIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upload': typeof UploadRoute
  '/author/$name': typeof AuthorNameRoute
  '/track/$id': typeof TrackIdRouteWithChildren
  '/track/$id/edit': typeof TrackIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upload': typeof UploadRoute
  '/author/$name': typeof AuthorNameRoute
  '/track/$id': typeof TrackIdRouteWithChildren
  '/track/$id/edit': typeof TrackIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/library': typeof LibraryRoute
  '/my-submissions': typeof MySubmissionsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/upload': typeof UploadRoute
  '/author/$name': typeof AuthorNameRoute
  '/track/$id': typeof TrackIdRouteWithChildren
  '/track/$id/edit': typeof TrackIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/home'
    | '/library'
    | '/my-submissions'
    | '/profile'
    | '/reset-password'
    | '/upload'
    | '/author/$name'
    | '/track/$id'
    | '/track/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/home'
    | '/library'
    | '/my-submissions'
    | '/profile'
    | '/reset-password'
    | '/upload'
    | '/author/$name'
    | '/track/$id'
    | '/track/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/favorites'
    | '/home'
    | '/library'
    | '/my-submissions'
    | '/profile'
    | '/reset-password'
    | '/upload'
    | '/author/$name'
    | '/track/$id'
    | '/track/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LibraryRoute: typeof LibraryRoute
  MySubmissionsRoute: typeof MySubmissionsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UploadRoute: typeof UploadRoute
  AuthorNameRoute: typeof AuthorNameRoute
  TrackIdRoute: typeof TrackIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$name': {
      id: '/author/$name'
      path: '/author/$name'
      fullPath: '/author/$name'
      preLoaderRoute: typeof AuthorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id/edit': {
      id: '/track/$id/edit'
      path: '/edit'
      fullPath: '/track/$id/edit'
      preLoaderRoute: typeof TrackIdEditRouteImport
      parentRoute: typeof TrackIdRoute
    }
  }
}

interface TrackIdRouteChildren {
  TrackIdEditRoute: typeof TrackIdEditRoute
}

const TrackIdRouteChildren: TrackIdRouteChildren = {
  TrackIdEditRoute: TrackIdEditRoute,
}

const TrackIdRouteWithChildren =
  TrackIdRoute._addFileChildren(TrackIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LibraryRoute: LibraryRoute,
  MySubmissionsRoute: MySubmissionsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UploadRoute: UploadRoute,
  AuthorNameRoute: AuthorNameRoute,
  TrackIdRoute: TrackIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
